spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring
    username: root
    password: 040bff1401e51a24e8f82d273288abca
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      connect-timeout: 2s
      timeout: 2s

logging:
  level:
    com.cat.hard: DEBUG

app:
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    expiration: 7d
